version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis/redis-stack:latest"
    container_name: redis-local
    ports:
      - "6379:6379"
      - "8001:8001"
  server:
    image: server:latest
    container_name: server
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      QUEUE_HOST: rabbitmq
      QUEUE_PORT: 5672
      QUEUE_USER_NAME: guest
      QUEUE_USER_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_EXPIRY_SECONDS: 10000
    depends_on:
      - rabbitmq
      - redis
  worker:
    image: worker:latest
    container_name: worker
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3000
      QUEUE_HOST: rabbitmq
      QUEUE_PORT: 5672
      QUEUE_USER_NAME: guest
      QUEUE_USER_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_EXPIRY_SECONDS: 10000
    depends_on:
      - rabbitmq
      - redis
    pids_limit: 60 # Max number of processes running in thw container.
    cpus: 1 # No of CPUs allocated
    mem_limit: 150M # Hard limit
